### ISSUE TITLE
Unkown HID devices (Surface Laptop 3 AMD)

### ISSUE THREAD

**Issue by fxgsell** [linux-surface/surface-aggregator-module#30]
Found those unkown devices, touchscreen or accelerometer?

Any data I could provide to help supporting them?

```
$ cat /proc/bus/input/devices | grep "Name\|Sysfs"
...
S: Sysfs=/devices/platform/MSHW0110:00/surface_sam_sid_vhf/0006:045E:0922.0001/input/input23
N: Name="Microsoft Surface HID UNKNOWN"
S: Sysfs=/devices/platform/MSHW0110:00/surface_sam_sid_vhf/0006:045E:0922.0001/input/input24
N: Name="Microsoft Surface HID UNKNOWN"
S: Sysfs=/devices/platform/MSHW0110:00/surface_sam_sid_vhf/0006:045E:0922.0001/input/input26
N: Name="Microsoft Surface HID UNKNOWN"
S: Sysfs=/devices/platform/MSHW0110:00/surface_sam_sid_vhf/0006:045E:0922.0001/input/input27
```

**Comment by qzed** [comment]
The `UNKNOWN` suffix is created automatically by the hid-multitouch driver (https://elixir.bootlin.com/linux/v5.4.7/source/drivers/hid/hid-multitouch.c#L1584), similar to `Mouse` and `Keyboard` suffixes (in other hid drivers). `UNKNOWN` means that the driver can't pin them to a specific category, however, they should still work fine as normal input devices, as the HID records emmitted by them are still being parsed and translated to input events in the kernel.

**Comment by fxgsell** [comment]
Thank you

**Comment by fxgsell** [comment]
Thank you
