### ISSUE TITLE
People wanting to test Surface Pro X

### ISSUE THREAD

**Issue by Dmole** [linux-surface/surface-aggregator-module#53]
https://github.com/Sonicadvance1/linux/issues/27

**Comment by thmichel** [comment]
Hin, would be happy to test Linux on my Pro X. Are there any build instructions?

**Comment by qzed** [comment]
@thmichel You might get more help for that on https://github.com/Sonicadvance1/linux/issues/27. There are also a [link](https://build.opensuse.org/package/show/home:lkocman:aarch64-laptops/kernel-source) to an openSUSE build service repo. Building the kernel should be fairly standard, but you'll probably need the appropriate patches and config options.

**Comment by thmichel** [comment]
I built the kernel now using WSL on Windows. Problem is I cannot get the Pro X to boot the Linux image provided in your link, so I cannot install Linux in the first place.

**Comment by qzed** [comment]
Can't really help with that as I've never tried linux on Android, sorry.

**Comment by mirh** [comment]
Progresses have been made, thanks also to linaro.

**Comment by qzed** [comment]
For Surface Pro X support, see https://github.com/Sonicadvance1/linux/issues/27 and https://github.com/linux-surface/surface-pro-x. While the changes haven't been included in this repository yet, we now do have SAM support for most parts (keyboard, touchpad, battery stats).
